POST http://localhost:3000/api/post/create/comments
Content-Type: application/json

{
  "title": "Next.js",
  "content": "Subiendo de nivel con Next.js",
  "comments": [
    {
      "content": "Recomendado por Jhon Doe"
    }
  ]
}
